devonf: remove 'in-tree' ocp2138.ko from devonf
Devong 5G ROW is using ocp2138.ko 'out-of-tree' driver
version and also includingthe 'in-tree' version as part of
its kernel config.
This is causing build failures at latest mainline builds.
Removing 'in-tree' dlkm temporarily to fix the following build
failure:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: VENDOR_RAMDISK: drivers/gpu/drm/panel/
     dsi-panel-mot-tianma-nt36672c-649-fhdp-dphy-vdo-120hz.ko:
    required but not found in ko_order_table.csv -
     drivers/gpu/drm/panel/ocp2138.ko
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: Ifc2d9bfa8eeb87b12fa256da843189dc24d83176
Reviewed-on: https://gerrit.mot.com/2669852
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Felipe Carrasco <carrasco@motorola.com>
Submit-Approved: Felipe Carrasco <carrasco@motorola.com>
Tested-by: Felipe Carrasco <carrasco@motorola.com>
Reviewed-by: Bruno Oliveira <brunosoe@motorola.com>
Reviewed-by: Marcos Sassahara <msassaha@motorola.com>