[ALPS04292325] mrdump: fix build error of redifition
[Detail]
Build error:
1. static declaration of aee_rr_curr_exp_type follows
   non-static declaration
2. conflicting types for aee_sram_fiq_save_bin
3. attribute declaration must precede definition
4. redefinition of aee_sram_fiq_log

[Solution]
clean up repetitive codes.

MTK-Commit-Id: 00c4f2d41355593d18ce90ee736a8d0e654cead5

Change-Id: I85820543ebb58925238828330f6a010a33a1b224
Signed-off-by: MY Chuang <my.chuang@mediatek.com>
CR-Id: ALPS04292325
Feature: Memory RAM Dump (MRDUMP)
(cherry picked from commit 712b9001542c796f1e69a17a043e7d1b0c6562f5)