[ALPS03439544] timer: fix build error
[Detail] fix build error:
implicit declaration of function sched_clock

MTK-Commit-Id: 4efc2fc9ff832284de09ec84d257a416376bd25b

Change-Id: Ic8f3ccda3d42fcf90f49b5defab3b70ff82f2364
Signed-off-by: rita.chan <rita.chan@mediatek.com>
CR-Id: ALPS03439544
Feature: Others
(cherry picked from commit 63e05e7d81e380ac056fa20237d464feddd2ea87)