misc/cam_cal: fix struct redefinition
Gnevan build failed as below:
kernel-4.19/drivers/misc/mediatek/cam_cal/src/mt6768/camera_project/corfu/custom_eeprom_driver.h:118:8:
error: redefinition of 'stCAM_CAL_DATAINFO_STRUCT'

Remove stCAM_CAL_DATAINFO_STRUCT definition because it was already defined
in cam_cal_define.h by (CR)

Change-Id: If05713b351fcc83615feccd5154ba360495d3fc2
Reviewed-on: https://gerrit.mot.com/2389281
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Qiong Xie <xieq2@motorola.com>
Submit-Approved: Jira Key