arm64/config: tesla: remove unused panel drivers
Remove unused panel drivers from tesla build to avoid build failures
such as below.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: modpost: "_gate_ic_Power_off" [drivers/gpu/drm/panel/
    panel-alpha-samsung-s6e3hae-wqhd-dphy-cmd-120hz.ko] undefined!
ERROR: modpost: "_gate_ic_i2c_panel_bias_enable" [drivers/gpu/drm/panel/
    panel-alpha-samsung-s6e3hae-wqhd-dphy-cmd-120hz.ko] undefined!
ERROR: modpost: "_gate_ic_Power_on" [drivers/gpu/drm/panel/
    panel-alpha-samsung-s6e3hae-wqhd-dphy-cmd-120hz.ko] undefined!
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: I9da49ac90e3881d5fc0f6ee19721d511ff41215a
Reviewed-on: https://gerrit.mot.com/2579669
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Marcelo Pincinato <mpcinato@motorola.com>
Submit-Approved: Jira Key