ANDROID: Fix implicit enum conversion in ufs
A backport for HID support declared new attribute idns as part of a new
anonymous enum instead of enum attr_idn to preserve the android16-6.12
ABI. These were not cast to the correct enum when used, causing the
kernelci build errors l(CR) the following:

drivers/ufs/core/ufs-sysfs.c: In function ‘analysis_trigger_store’:
drivers/ufs/core/ufs-sysfs.c:1681:25: error: implicit conversion from ‘enum <anonymous>’ to ‘enum attr_idn’ [-Werror=enum-conversion]
 1681 |                         QUERY_ATTR_IDN_HID_DEFRAG_OPERATION, &mode);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Cast QUERY_ATTR_IDN_HID_* to enum attr_idn.

Fixes: ba125a42ce6e ("BACKPORT: FROMGIT: scsi: ufs: core: Add HID support")
Change-Id: I9c690b3feb17f64d54cb218acba92ce4b128e4de
Signed-off-by: Tiffany Yang <ynaffit@google.com>