Revert "(CR) linux/include: add sensors.h for single tap"
The header file within the kernel is taking precedence over the motorola
sensors.h, resulting in the following build failure:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
motorola/kernel/modules/drivers/input/touchscreen/touchscreen_mmi/
    touchscreen_mmi_gesture.c:512:10: error: use of undeclared identifier
    'SENSOR_TYPE_MOTO_TOUCH_PALM'
        .type = SENSOR_TYPE_MOTO_TOUCH_PALM,
                ^
1 error generated.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

This reverts commit 0f4a670225a4cbd54d321bd94e7ba76d094ae1af.

Change-Id: If2be4c2c4bbc62e4a96387c56eb4ccd5c759cb80
Reviewed-on: https://gerrit.mot.com/2830297
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Gilberto Gambugge Neto <gambugge@motorola.com>
Submit-Approved: Gilberto Gambugge Neto <gambugge@motorola.com>