sensors-1.0: fix include path for scp.h
Header include path needed to be changed due to updates from latest
mtk drop (t-alps-release-s0.mp1.tc2sp-V2.1).

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
kernel-4.19/drivers/misc/mediatek/scp/cm4/scp_feature_define.h:9:10:
    fatal error: 'scp.h' file not found
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: I64a2814889d3444898b32eadbfe55c791b8378ea
Reviewed-on: https://gerrit.mot.com/2228935
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Submit-Approved: Jira Key
Tested-by: Jira Key
Reviewed-by: Carlos Pinho <cpinho@motorola.com>
Reviewed-by: Rafael Ortolan <rafones@motorola.com>