[ALPS03637258] k71: WALT: build error
[Detail]
WALT doesnt support 32bit for compiling.
error "undefined reference to `__aeabi_uldivmod;"
fix it using macro div64_u64().

MTK-Commit-Id: 3d98b4eb29543e0f9fa8951097d32508cfbbdc0d

Change-Id: Ie9371984e288579674f31ddebf6a25b6409ce64b
CR-Id: ALPS03637258
Feature: Sched
Signed-off-by: Michael Jiang <michael.jiang@mediatek.com>