[ALPS03729865] mtk-cmdq: remove redefinition of pr_xxx
[Detail]
remove redefinition of pr_xxx

[Solution]
porting from http://gerrit.mediatek.inc:8080/#/c/1055891/

MTK-Commit-Id: 17075a2777d6008d8ddf01a55c4d7c4fe217c24e

Change-Id: I1efd167e13a28854505f9c43a209ea92e0507434
Signed-off-by: Houlong Wei <houlong.wei@mediatek.com>
CR-Id: ALPS03729865
Feature: mtk-cmdq
(cherry picked from commit 82a29bd84844d45ce1e3a6513d014a07b54a1bbb)