EKmoto_e6sROW-5803:[APVI] Improper selinux policy(8)
Description:
Motorola e6s device (released in 2020) mistakenly exposes
/dev/mtk_cmdq device to unprivileged users, which may
unnecessarily enlarge the potential attack surface.
The selinux policy for mtk_cmdq is:
(allow appdomain mtk_cmdq_device (chr_file (ioctl read open)))

Solution:
Merge MTK patch: ALPS04953743,ALPS05102507
Fix compile error:
/Work/code/moto_e6s/kernel-4.9/drivers/misc/mediatek/cmdq/v3/cmdq_mdp_common.c:1080:2:
error: ignoring return value of 'copy_from_user', declared with attribute
warn_unused_result [-Werror=unused-result]
  copy_from_user(p_metadatas, CMDQ_U32_PTR(secData->addrMetadatas)

St-result: NA

Change-Id: If74cec22856e1373b5c0c4424a1cc5eee4deca10