lyriq: change kconfig type to bool
The config CONFIG_MOT_LYRIQ is always being defined for other products
(e.g. austin) as an empty string. ChanGing the type to boolean as this
suits better for this config and to avoid unwanted definitions.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
kernel-4.19/drivers/misc/mediatek/imgsensor/src/mt6853/camera_hw_mt6833/
    imgsensor_cfg_table.c:36:5: error: use of undeclared identifier
    'IMGSENSOR_HW_PIN_AFVDD'; did you mean 'IMGSENSOR_HW_PIN_AVDD'?
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: Iaebf933465f706a3c52ffc6218b60cd829b747a9
Reviewed-on: https://gerrit.mot.com/2413535
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Carlos Pinho <cpinho@motorola.com>
Tested-by: Jira Key
Submit-Approved: Jira Key