[ALPS05453723] IOMMU: Fix build error without MTK_AEE_FEATURE
[Root cause]
If MTK_AEE_FEATURE is configured, IOMMU can build pass. But if
MTK_AEE_FEATURE is closed, IOMMU will build fail.
Error log is as below:

error: field has incomplete type struct mutex
struct mutex ctx_lock;

So, if MTK_AEE_FEATURE is closed, IOMMU will not include
linux/mutex.h without aee.h.

[Solution]
Add "include linux/mutex.h" to pseudo_m4u_gz_sec.h

MTK-Commit-Id: d549b2970553d045b9aa5466fdb461f41eb248cb

Change-Id: I6abb9eb1a782f6da9db7ce52437f9cd5806689c7
Signed-off-by: Chao Hao <chao.hao@mediatek.com>
CR-Id: ALPS05453723
Feature: IOMMU