charger: Fix build error for mtk_charger
To fix:
mtk_charger.c:3071:7: error: variable 'icl' is used uninitialized
whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
So we need to initialize variable 'icl'.

Change-Id: I9dec1920d96656abb4eedb43f1ff5a13f8dffc6e
Signed-off-by: Guocheng Wang <wanggc6@motorola.com>
Reviewed-on: https://gerrit.mot.com/2502798
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Haijian Ma <mahj8@motorola.com>
Reviewed-by: Huosheng Liao <liaohs@motorola.com>
Submit-Approved: Jira Key