[ALPS02767202] iommu/mediatek: Select ARM_DMA_USE_IOMMU
The newly added Mediatek IOMMU driver uses the IOMMU_DMA infrastructure,
but unlike other such drivers, it does not select ARM_DMA_USE_IOMMU,
which is a prerequisite, leading to a link error:

warning: (MTK_IOMMU) selects IOMMU_DMA which has unmet direct dependencies
(IOMMU_SUPPORT && NEED_SG_DMA_LENGTH)
drivers/iommu/built-in.o: In function `iommu_put_dma_cookie:
mtk_iommu.c:(.text+0x11fe): undefined reference to `put_iova_domain
drivers/iommu/built-in.o: In function `iommu_dma_init_domain:
mtk_iommu.c:(.text+0x1316): undefined reference to `init_iova_domain
drivers/iommu/built-in.o: In function `__iommu_dma_unmap:
mtk_iommu.c:(.text+0x1380): undefined reference to `find_iova

This adds the same select that the other drivers have. On a related
note, I wonder if we should just always select ARM_DMA_USE_IOMMU
whenever any IOMMU driver is enabled. Are there any cases where
we would enable an IOMMU but not use it?

MTK-Commit-Id: 13a21212018d59f16692c5481dcf865a3673a2ea

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 0df4fabe208d ("iommu/mediatek: Add mt8173 IOMMU driver")
Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit 1928832f0241f0c39fcd2ce73aaa39d37db50a97)
CR-Id: ALPS02767202
Feature: IOMMU
Signed-off-by: rita.chan <rita.chan@mediatek.com>
Change-Id: Ic83411cdf64c9d0bd81acaf256cc94a1ba8e5076