[ALPS02875518] blocktag: fix build fail when MODULES is enable
When CONFIG_MODULES is enabled, blocktag.c build fail with:
drivers/misc/mediatek/blocktag/blocktag.c:229:1: error: expected , or ; before static

Add the missing ;

MTK-Commit-Id: 0444a9557c665ca1693533e8ae50487881b42782

Change-Id: Ia82c2eec6cdb50b7d8f6fe07497d4d7fd76d4f1a
Signed-off-by: Yingjoe Chen <yingjoe.chen@mediatek.com>
CR-Id: ALPS02875518
Feature: others