[ALPS02767202] iommu/mediatek: Mark PM functions as __maybe_unused
When CONFIG_PM is unset, we get a harmless warning for this driver:

drivers/iommu/mtk_iommu.c:665:12: error: mtk_iommu_suspend defined
but not used [-Werror=unused-function]
drivers/iommu/mtk_iommu.c:680:12: error: mtk_iommu_resume defined
but not used [-Werror=unused-function]

Marking the functions as __maybe_unused gits rid of the two functions
and lets the compiler silently drop the object code, while still
doing syntax checking on them for build-time verification.

MTK-Commit-Id: c4964e42118aa47970b1eb44eefe4cb4172408ee

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 0df4fabe208d ("iommu/mediatek: Add mt8173 IOMMU driver")
Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit fd99f796a20b1a805c80ee51d7349d65103e7aaf)
CR-Id: ALPS02767202
Feature: IOMMU
Signed-off-by: rita.chan <rita.chan@mediatek.com>
Change-Id: I7931cc4f37cb9025722d6d88162127a54f3eabd0