[ALPS03439544] timer: fix build error
[Detail] fix build error:
implicit declaration of function sched_clock

MTK-Commit-Id: 426a04069186372a8408b166413cc1d95904f917

Change-Id: Ic8f3ccda3d42fcf90f49b5defab3b70ff82f2364
Signed-off-by: Stanley Chu <stanley.chu@mediatek.com>
CR-Id: ALPS03439544
Feature: Others
(cherry picked from commit 63e05e7d81e380ac056fa20237d464feddd2ea87)