[ALPS09563439] ACK: dependency change: fix build error
[Description]

This is caused by ACK change "cf0c713c694641 sched/fair:
set_load_weight() must also call reweight_task() for SCHED_IDLE tasks"

/tmp/src_kernel/kernel/kernel-5.10/drivers/misc/mediatek/task_turbo/task_turbo.c:592:20:
error: incompatible integer to pointer conversion passing 'int' to
parameter of type 'const struct load_weight *'
[-Werror,-Wint-conversion]
                reweight_task(p, prio);
                                 ^~~~
/tmp/src_kernel/kernel/kernel-5.10/kernel/sched/sched.h:1996:76: note:
passing argument to parameter 'lw' here
extern void reweight_task(struct task_struct *p, const struct
load_weight *lw);
                                                                           ^
1 error generated.
make[5]: ***
[/tmp/src_kernel/kernel/kernel-5.10/scripts/Makefile.build:273:
drivers/misc/mediatek/task_turbo/task_turbo.o] Error 1
make[4]: ***
[/tmp/src_kernel/kernel/kernel-5.10/scripts/Makefile.build:516:
drivers/misc/mediatek/task_turbo] Error 2

[Test]
build pass, boot pass

Change-Id: I2fc4614db0239c416924abd58386c765013098a9
CR-Id: ALPS09563439
Feature: Kernel SI Operation
Signed-off-by: Bosser Ye <bo.ye@mediatek.com>
Signed-off-by: Robert Cabral <robertc@motorola.com>
Reviewed-on: https://gerrit.mot.com/3345193
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Rafael Ortolan <rafones@motorola.com>
Reviewed-by: Bruno Oliveira <brunosoe@motorola.com>
Reviewed-by: Deise Alves <deisema@motorola.com>
Submit-Approved: Deise Alves <deisema@motorola.com>