[ALPS04715419] Platform: K57p project buiderror fix
mtk_udi.c:146:41: error: macro "mt_secure_call"
requires 5 arguments, but only 4 given

MTK-Commit-Id: 5593d46960ea672d9c8e131a51858c104e813746

Change-Id: I5e1f2597ab678ebaa7a6d6662706ba291841af27
CR-Id: ALPS04715419
Feature: Configuration
Signed-off-by: Yogesh Tundele <yogesh.tundele@mediatek.com>