[ALPS03532453] PMU: config MT6370 to k63v1us_64
[Detail]
Error: mt6370_pmu cant found in main dtb
Add MT6370 Config and DTS node to fix it.

MTK-Commit-Id: 5e6ceafa696cbd1c8eb2dbce88a6a69ff093ded0

Change-Id: I58f812a3fa87b10afe8c22ee265a41a358381f50
Feature: PMU
CR-Id: ALPS03532453
Signed-off-by: Juju Sung <juju.sung@mediatek.com>
(cherry picked from commit 42b70a3ac4489eb2f4e166b5521d1ea226b45c0e)