austin: fix mmc node name
The mmc node name changed from 'msdc1' to 'mmc1' at the mt6833 device
tree.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: ufdt_overlay_do_fixups():Couldn't find 'msdc1' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: If895b78dca3e33299e2afc383ed5b3ce0fe77bd2
Reviewed-on: https://gerrit.mot.com/2379306
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Submit-Approved: Jira Key
Tested-by: Jira Key
Reviewed-by: Rafael Ortolan <rafones@motorola.com>
Reviewed-by: Carlos Pinho <cpinho@motorola.com>