[ALPS03469399] ANDROID: Fix missing header file for get_cmdline() call
commit ab6f11cf39b6a605b0e644ac1fde21d517d56d40
uid_sys_stats: log task io with a debug flag
causes on some builds next error:
error: implicit declaration of function get_cmdline
[-Werror=implicit-function-declaration]

Signed-off-by: Dmitry Shmidt <dimitrysh@google.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>

MTK-Commit-Id: 233af48bf787c4321e192aa7fc7f3e651c64aaa9

Change-Id: I795ba353a83a3775cf0844807d725eb4eb719809
Signed-off-by: rita.chan <rita.chan@mediatek.com>
CR-Id: ALPS03469399
Feature: kernel
(cherry picked from commit 246abea9eb6707360b8d67dc1be5b0ef0ed94070)