[ALPS04140405] mdla: fix build warnings
fix build warnings that converted to errors:

mdla_main.c:3946:21: error: cast from pointer to integer of
  different size
mdla_main.c:1561:6: error: "ret" may be used uninitialized
  in this function
mdla_proc.c:71:2: error: ignoring return value of
  "copy_to_user", declared with attribute warn_unused_result

... and more.

MTK-Commit-Id: 73986586067269c9042ce220576b24238f32355c

Change-Id: I0d080e5dbdd32f0406a4aff227eb99231653ca24
Signed-off-by: Perry Hsu <perry.hsu@mediatek.com>
CR-Id: ALPS04140405
Feature: MDLA Platform