[ALPS02788148] spm suspend: fix build error
[Detail]
Fix the following build error,
kernel-4.4/drivers/misc/mediatek/base/power/spm_v2/mtk_spm_sleep.c:665
 error: pcmdesc may be used uninitialized in this function

MTK-Commit-Id: c325d48fd0f5ed9b497142190657e5cc19b79ff3

Change-Id: I203e55123a68bde45c39d90653b6ef8eb8b521d2
Signed-off-by: Major Lee <major.lee@mediatek.com>
CR-Id: ALPS02788148
Feature: BSP : Power Consumption(*)
(cherry picked from commit 648c309ea45d1843512880001dc368bd42314293)