[ALPS02875518] blocktag: fix build fail when MODULES is enable
When CONFIG_MODULES is enabled, blocktag.c build fail with:
drivers/misc/mediatek/blocktag/blocktag.c:229:1: error: expected , or ; before static

Add the missing ;

MTK-Commit-Id: d4be38d77fe0ea3e1cbe84c2eb72a84bc54a4921

Change-Id: Ia82c2eec6cdb50b7d8f6fe07497d4d7fd76d4f1a
Signed-off-by: rita.chan <rita.chan@mediatek.com>
CR-Id: ALPS02875518
Feature: others