[ALPS02788148] spm suspend: fix build error
[Detail]
Fix the following build error,
kernel-4.4/drivers/misc/mediatek/base/power/spm_v2/mtk_spm_sleep.c:665
 error: pcmdesc may be used uninitialized in this function

MTK-Commit-Id: 0e736ebc44fd377ea8aa5a615a77c3d36b7640a7

Change-Id: I203e55123a68bde45c39d90653b6ef8eb8b521d2
Signed-off-by: rita.chan <rita.chan@mediatek.com>
CR-Id: ALPS02788148
Feature: BSP : Power Consumption(*)
(cherry picked from commit 648c309ea45d1843512880001dc368bd42314293)