aw883xx: change reference type to non overloadable operator (.)
The 'struct aw_monitor_desc' is not being declared anymore as a pointer,
so adjust its reference at the code.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
kernel-4.19/sound/soc/codecs/aw883xx/aw883xx.c:1394:56: error: member
       reference type 'struct aw_monitor_desc' is not a pointer; did you
       mean to use '.'?
     cancel_delayed_work_sync(&aw883xx->aw_pa->monitor_desc->delay_work);
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: Ia4ea03c7ccf565345f900a6e99a8f3d7cf4fb523
Reviewed-on: https://gerrit.mot.com/2385991
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Submit-Approved: Jira Key
Tested-by: Jira Key
Reviewed-by: Rafael Ortolan <rafones@motorola.com>
Reviewed-by: Carlos Pinho <cpinho@motorola.com>