[ALPS04766989] mm/memcontrol: fix mismerge 4.9.190
Fix the following build error caused by mismerge.

error: redefinition of invalidate_reclaim_iterators
error: invalidate_reclaim_iterators defined but not used
[-Werror=unused-function]

MTK-Commit-Id: 7506205fe44ba73a6a938210941b4edfa8f7d77b

Change-Id: Id9bdb5da0f8076bc0e9a3c6e3f598f3306571983
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
Feature: [Module]Kernel Memory Management
CR-Id: ALPS04766989