[ALPS03764147] sched: fix Clang warning
[Detail]
Fix CLANG warning
../kernel/sched/eas_plus.c:166:9: error: static variable
system_overutil is used in an inline function with external linkage
[-Werror,-Wstatic-in-inline]

MTK-Commit-Id: dcde7c357de08f193a064609467d2d748797bba3

Change-Id: Ic2c613e940a66067eb031fe8fc14b1c477ce84af
Signed-off-by: YT Chang <yt.chang@mediatek.com>
CR-Id: ALPS03764147
Feature: build process