kyoto: fix mmc node name
The mmc node name changed from 'msdc1' to 'mmc1' at the mt6853 device
tree.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: ufdt_overlay_do_fixups():Couldn't find 'msdc1' symbol in main dtb
ERROR: ufdt_overlay_apply():failed to perform fixups in overlay
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

ref.: https://gerrit.mot.com/#/c/2379306/

Change-Id: Ie5040b72c162db062dca0300db31fd0356544596
Reviewed-on: https://gerrit.mot.com/2830167
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Rafael Ortolan <rafones@motorola.com>
Reviewed-by: Bruno Oliveira <brunosoe@motorola.com>
Reviewed-by: Carlos Pinho <cpinho@motorola.com>
Submit-Approved: Gilberto Gambugge Neto <gambugge@motorola.com>
Tested-by: Gilberto Gambugge Neto <gambugge@motorola.com>