[ALPS04297952] usb20: fix ununsed-function build errors
Fix unused-function build errors when compiling with clang by
move the functions under proper config options.

drivers/misc/mediatek/usb20/mt6765/usb20_host.c:221:13:
error: unused function mt_usb_vbus_on [-Werror,-Wunused-function]
drivers/misc/mediatek/usb20/mt6765/usb20_host.c:227:13:
error: unused function mt_usb_vbus_off [-Werror,-Wunused-function]

MTK-Commit-Id: 3261cdb9e20cd2c970c70d1988ebe102e9558154

Change-Id: Idd7d2c0ed862621ba63bee50fd0b2521e891944c
Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS04297952
Feature: Build System