thermal/6853: remove ntc flashlight from kyoto
Kyoto doesn't support ntc flashlight, so removing it the driver from the device.
Also, its build was breaking after merging Lisbon bringup.

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
drivers/misc/mediatek/thermal/common/thermal_zones/mtk_ts_flashlight.c:1317:24:
error: use of undeclared identifier 'AUX_IN5_NTC'
                        g_RAP_ADC_channel = AUX_IN5_NTC;
                                            ^
1 error generated.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Change-Id: Ia160a6b3e4fcb6191c93898d9daf9c44af9f321b
Reviewed-on: https://gerrit.mot.com/2286175
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Reviewed-by: Marcelo Pincinato <mpcinato@motorola.com>
Submit-Approved: Marcelo Pincinato <mpcinato@motorola.com>
Tested-by: Marcelo Pincinato <mpcinato@motorola.com>