ACK: Fix build error
error: implicit declaration of function 'ufshcd_vops_setup_xfer_req'

Removed by ACK patch "3586ade72bf40b04171c91897e6df22b91e25bb3"

Mot-CRs-fixed: (CR)
Change-Id: Ia8fa7f167a75664b396353a1e36b7e7fc5cc5292
CR-Id: ALPS07767442
Feature: Kernel SI Operation
Signed-off-by: Bo Ye <bo.ye@mediatek.com>
Reviewed-on: https://gerrit.mot.com/2467234
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Zhihong Kang <kangzh@motorola.com>
Submit-Approved: Jira Key